CREATE TABLE workout
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(50) NOT NULL,
    notes      TEXT,
    user_id    BIGINT      NOT NULL,

    CONSTRAINT fk_workout_user
        FOREIGN KEY (user_id)
            REFERENCES users (id),

    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now()
)