CREATE TABLE workoutexercise
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id  BIGINT NOT NULL,
    exercise_id BIGINT NOT NULL,
    sets        INT    NOT NULL,
    reps        INT    NOT NULL,
    weight      INT    NOT NULL,

    CONSTRAINT fk_workout_workoutexercise
        FOREIGN KEY (workout_id)
            REFERENCES workout (id),

    CONSTRAINT fk_exercise_workoutexercise
        FOREIGN KEY (exercise_id)
            REFERENCES exercise (id)

)